name: Deploy Managed Application
run-name: Deploying Managed solution ${{ github.event.inputs.solution_name }} for ${{ github.event.inputs.environment_url }} environment
on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "name of the Solution"
        required: true
        default: LinearInputControlSolution
      # environment_id:
      #   description: "GUID of your Dataverse environment"
      #   required: true
      #   default: "GUID-OF-YOUR-ENVIRONMENT"
      environment_url:
        description: "http endpoint of your Dataverse environment"
        required: true
        default: "https://orgc147b5b9.crm.dynamics.com/"
      #solution_source_folder:
       # description: "Location of the solution files"
        #requried: true
        #default: .
      #solution_outbound_folder:
       # description: "solution outbound folder"
        #required: true
        #default: out/stage
env:
      #Update your values here
      CLIENT_ID: 'a88b1599-590d-4b7a-ace1-229dea7fc826'
      TENANT_ID: 'c9f44141-61a3-483a-b157-783e86287e36' 
jobs:
    import-managed-solution:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
        env:
          RUNNER_DEBUG: 1
      
      - name: Import solution as managed to build env
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{github.event.inputs.environment_url}}
          app-id: ${{env.CLIENT_ID}}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{env.TENANT_ID}}
          solution-file: ${{ github.event.repository.name}}/${{ github.event.inputs.solution_name }}_managed.zip
          force-overwrite: true
          publish-changes: true
  
